TYPE_KEYWORDS = {"INT", "FLOAT", "BOOLEAN", "CHAR_TYPE"}
COMPARISON_OPS = {"EQ", "NEQ", "LT", "GT", "LE", "GE"}
ARITHMETIC_OPS = {"ADD", "SUB", "MUL", "DIV", "MOD"}
ASSIGN_OPS = {"PLUSEQ", "MINUSEQ", "INCR", "DECR", "ASSIGN"}
LITERALS = {"INT_LIT", "FLOAT_LIT", "CHAR_LITERAL", "BOOL_TRUE", "BOOL_FALSE"}
FLOW_OPS = {"BREAK", "CONTINUE"}
BINARY_ASSIGN_OPS = {"+=", "-=", "="}
UNARY_ASSIGN_OPS = {"++", "--"}
